### PR TITLE
Upgrade Helix and some refactor

### PR DESCRIPTION
**Pull request by chancancode**
Hello, this is very cool project and a great use case for Helix!

I pulled the code to play with it a little bit locally. While I was at that I found some small improvements so I thought I should submit a PR.

I chunked up the changes and included a lot of details and benchmark results in the commit message. You may find it easier to review by reading the commits one-by-one. Feel free to cherry pick or edit them as you see fit.

Let me know if you have any questions. By the way, if you have any questions or suggestions for Helix please feel free to let me know (or open an issue). I would also like to know what are some missing features you might need for this library so we know how to prioritize them.

Thanks for trying Helix!!

### CODE REVIEW

**Comment by chancancode** [comment]
By the way, I am pretty sure the the `bytes_record_to_ruby` code can be rewritten to lean on the slice/vec/str coercion in Helix with basically no performance difference (especially if you rewrite it to use `StringRecrod` instead of `BytesRecord`). However, I don't understand that part of the code (and the csv library) fully so I left it untouched.

Furthermore, I suspect the split between `each` (defined in Ruby) and `each_internal` is not "necessary" and doesn't quite do what you think. Calling `rb_funcall` and `rb_yield` without `rb_protect` is highly unsafe and undefined behavior in Rust, as any Ruby exception (not only the `break` you attempted to handle) will jump through the Rust stack directly back into Ruby, skipping any necessary Rust unwinding. If that happens, it will cause serious memory corruption, turning the Ruby process into a segfault time bomb, so rescuing the `StopIteration` from Ruby at that point probably doesn't add that much value.

We are working on making a completely safe version of that API, but since you seem perfectly capable of figuring out the raw C-API, you can probably just do the necessary `rb_protect` dance within the Rust code and drop the `each` vs `each_internal` split. 😄

**Comment by lautis** [comment]
Thanks! I'll need to look into `rb_protect`. For the exception handling my needs have been quite limited so far. 😊

Regarding Helix features, binary distribution would be great. I assume there will be more gems like this around when you don't need to have rustc installed or depend on the exact Helix version in all gems.

**Comment by chancancode** [comment]
Thanks for the quick review!

For your reference – I mentioned in the commit message that I thought the last commit is somewhat inelegant (although the ownership issue is fundamental). I came up with an alternative closer to the original, which contains/limits the coercion leakage but still avoid writing unsafe code: https://github.com/chancancode/rscsv/commit/d6c4f609e815dac1b13bfaf9d43ea819bc25ecaa

In my quick testing it seems _marginally_ slower, and I couldn't figure out why. In theory, it should be the same amount of work as the approach in this PR. Perhaps I am just not juggling some things correctly. I'll leave that here for you to look into, if you are interested.

**Comment by chancancode** [comment]
@lautis I forgot to mention – for binary distribution, check out the thread on https://github.com/Fosslim/license_matcher/issues/10

We need to smooth out the process and include it by default in the generators, but I am sure you can figure out how to replicate it in the mean time. I think something like that plus what you did here (requiring the rust compiler in the extconf for “other platforms”) is the way to go.

**Pull request merged**
